pattern_matcher/grammars/CyboxPattern.g4
pattern_matcher/grammars/CyboxPatternListener.py
pattern_matcher/grammars/CyboxPatternParser.py
pattern_matcher/matcher.py

This adds support for the same-root-object restriction: 'AND' in a comparison expression now implies that
the same 'root' cybox object must match both sub-expressions.
Also:
- An additional bookkeeping change was made, to simplify the code implementing the above restriction (in exitComparisonExpression()): path stepping state and prop test structure are now obs_idx->data maps, instead of a list of (obs_idx, data) 2-tuples.
- If order comparison ('>', '<', etc) is not supported between two types, the result is False instead of causing an error.  (This means that both 'a < b' and 'a >= b' is false for two values 'a' and 'b' for which order comparison isn't supported.  Which could be considered.... unnatural.)
- Usage of the 'NOT' operator inside comparison expressions has changed.  Now, …

Support for same-root-object restriction

---

stix2matcher/matcher.py

It needs to go through _literal_terminal_to_python_val(), because changing it to a string literal opens up all the string literal escaping possibilities, which need to be handled.  The old regex literal didn't have to worry about that.  Handling escaping is the job of the coercers.
Speaking of which, string literal escaping style in the matcher is no longer spec-compliant.  But it should just need a fix in the coercer, and all users of string literals should get the updated handling for free, provided they're using the aforementioned function.

Fix how the regex string is obtained in exitPropTestRegex().

---

stix2matcher/grammars/STIXPattern.g4

I tried running the tests with a parser generated with the recently-released ANTLR 4.6.  I was curious to see if there would be any compatibility problems.  I did find one problem, which was that it errored out due to invalid escape sequence '\v' [1].  I suspect this was also invalid in earlier versions of ANTLR, but was silently ignored.  I've been seeing that squiggly red underline in my IDE for a long time.
My guess is that it was intended to represent a vertical tab character.  I found a vertical tab character in the unicode standard as U+000B, so I switched to that instead.
1. https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements

Changed invalid whitespace escape sequence '\v' to '\u000B'

---

stix2matcher/matcher.py

The file-related I/O code for commandline functionality, was messy.  The text files needed to be opened in a textual mode with a proper encoding, but python2's argparse.FileType doesn't support that.  And even if it did, using it wouldn't allow the encoding to be settable via another commandline parameter.  So I ditched argparse.FileType and switched to normal string params, opened manually via io.open() (python2's plain open() function also doesn't support setting an encoding).
Also, I thought I had the logging working with unicode characters, but I found it was still crashing when attempting to print funny characters to the console, using a codec that didn't support those characters.  So decided to run all values through the "unicode_escape" codec to ensure everything is printable.  And …

Encoding-related fixes

---

stix2matcher/matcher.py

Errors occurred when using temporal qualifiers (WITHIN, START/STOP) with bindings which contained 'None'.  It is a simple fix, I'd simply forgotten to update the code in a couple places.
There should be additional test cases to cover this, but I'm planning on adding them with a separate pull request.  I stumbled across this bug when making a separate change, which I thought made more sense as a separate PR.

Fixed bugs related to 'None' bindings.

---

stix2matcher/matcher.py
stix2matcher/test/test_unicode_normalization.py

Also added unicode normalization tests.
I did not do NFC normalization for the set 'IN' operator.  I thought it made more sense for that to remain consistent with the behavior of the '=' operator, although the spec implies that normalization should be done in that case too.  (This should probably be verified.)

Added unicode NFC normalization to LIKE and MATCHES operators

---

stix2matcher/matcher.py
stix2matcher/test/test_basic_ops.py
stix2matcher/test/test_null.py
stix2matcher/test/test_timestamps.py

Added new tests to cover some of what the old test_pattern_matcher.py file used to cover.  test_basic_ops.py actually has *many* more tests than the old file, but still isn't a complete replacement.
These tests uncovered some issues, which are fixed:
- When a timestamp in a pattern is compared to a string from json, the matcher attempts to convert the json string to a timestamp.  The problem was that it wasn't checking if the json value actually was a string first.  Now, it does.  If the json value is not a string, the test result is 'false', not an error.  If the json value is a string, but is formatted incorrectly, that still results in an error.
- The above hackage was enabled for equality and order comparisons only.  With this PR, it is also added to set membership tests ('IN', 'NOT …

Bugfixes, adding more tests

---

stix2matcher/matcher.py
stix2matcher/test/test_matching_sdos.py

The match() function now returns matching SDOs, rather than just True or False.

Return matching sdos

---

stix2matcher/matcher.py
stix2matcher/test/test_references.py

I accidentally broke them in the PR which changed the matcher to return matching SDOs.  Oops.  Also added some tests so errors with references will hopefully be caught in the future.

Fix references.  I'd accidentally broken them.

---

stix2matcher/matcher.py

It works by replacing "literal names" in the parser with "symbolic names", where the literal name is "&lt;INVALID&gt;".  It's a hack, but a very simple way to address the problem.  An example of an improved error message is:
```
__main__.MatcherException: 1:24: mismatched input '<EOF>' expecting {IntLiteral, FloatLiteral, HexLiteral, BinaryLiteral, StringLiteral, TimestampLiteral}
```
So it relies on nice descriptive lexer rule names.  But I think the lexer rule names are pretty good.

Added a hack to reduce/eliminate the ugly "<INVALID>" tokens from parse errors

---

stix2matcher/matcher.py
stix2matcher/test/test_basic_ops.py
stix2matcher/test/test_binary.py
stix2matcher/test/test_comparison_exprs.py
stix2matcher/test/test_complex.py
stix2matcher/test/test_matching_sdos.py
stix2matcher/test/test_null.py
stix2matcher/test/test_object_path_quoting.py
stix2matcher/test/test_observation_exprs.py
stix2matcher/test/test_references.py
stix2matcher/test/test_temporal_qualifiers.py
stix2matcher/test/test_timestamps.py
stix2matcher/test/test_unicode_normalization.py

This PR improves the behavior of the matcher with respect to temporal operators and qualifiers.  Both first and last observed timestamps on SDOs are now used.  A more sophisticated approach is taken which will allow more matches than before: if it is possible to choose a legal timestamp (i.e. between first_observed and last_observed inclusive) for each observation such that the the temporal constraints are satisfied, then the observation(s) pass the test.

Improved temporal operators

---

stix2matcher/matcher.py
stix2matcher/test/test_basic_ops.py

Changes corresponding to the latest grammar update, to add support
for the 'NOT' qualifier before equality and order comparison
operators.  Sprinkled some additional tests using this syntax into
test_basic_ops.py.

Add support for the 'NOT' qualifier before equality and order comparison operators.

---

stix2matcher/matcher.py

Fix a little bug that was introduced when I added support for 'NOT' before equality and order comparison operators.  It's only about an exception message, and in a code branch that probably will never be executed.  So, it's a minor thing.

Fix a little bug in an exception message

---

stix2matcher/matcher.py

Modifies the main() function to return a value of 1 when there
is a failure to match.
Also changes the verbiage to MATCH/NO MATCH.
Adds options for quiet(er) operation.
Returns `2` as an exit value when there are otherwise uncaught exceptions.
Fix for #40

Exit with a non-zero status when a pattern fails to match

---

stix2matcher/matcher.py
stix2matcher/test/test_basic_ops.py

Fixes for the behavior of the 'NOT' qualifier on the 'LIKE',
'ISSUBSET', and 'ISSUPERSET' operators.  Before, type-mismatched
comparisons would always evaluate to false.  Now, comparisons
including the 'NOT' operator, eval to true.
Updated tests in test_basic_ops.py according to the above pattern
matching changes.  Also added some type-mismatched tests of
the 'ISSUBSET' and 'ISSUPERSET' operators, which were missing
before.
Fixes #42.

Fixes for the behavior of the 'NOT' qualifier on some comparison operators

---

stix2matcher/matcher.py

... instead of trying to access self.__parse_tree directly.
Other part of the fix for [cti-pattern-validator issue #32](https://github.com/oasis-open/cti-pattern-validator/issues/32).

Change the Pattern.match() method to call self.walk()

---

setup.py
stix2matcher/matcher.py
stix2matcher/test/test_basic_ops.py
stix2matcher/test/test_binary.py
stix2matcher/test/test_comparison_exprs.py
stix2matcher/test/test_complex.py
stix2matcher/test/test_matching_sdos.py
stix2matcher/test/test_null.py
stix2matcher/test/test_observation_exprs.py
stix2matcher/test/test_references.py
stix2matcher/test/test_temporal_qualifiers.py
stix2matcher/test/test_timestamps.py
stix2matcher/test/test_unicode_normalization.py

The changes removed the IntLiteral token and replaced it with IntPosLiteral and IntNegLiteral, and similarly for FloatLiteral.  I think these matcher fixes were really necessitated by the aforementioned grammar changes which happened several months ago, not the changes I just recently made (which only changed the definitions of existing tokens and didn't introduce any new ones).
Also made it so negative list indices don't cause a matcher error.  The spec doesn't state that there should be an error, just that the comparison should eval to false.  See STIX 2.0 spec part 5 section 5.2.  Maybe there should be some additional tests which focus on object paths... I don't think there is a test which covers things like out-of-range list indices.
Had to fix some tests, since some syntax checking …

Fixed matcher according to pattern grammar changes (related to int and float tokens)

---

setup.py

Fixes #60 .
Remove direct dependency declaration on antlr4-python[23]-runtime from setup.py.  This should cause pattern-matcher to use the version of ANTLR which came with the pattern-validator, whatever that was.  So in the future, version conflicts between these two libraries will be impossible.

Remove direct dependency declaration on antlr4-python3-runtime

---

.travis.yml
setup.py
tox.ini

Python 3.8 has been released in October 2019 and it is expected that security updates until approximately October 2024.
See [PEP 569 -- Python 3.8 Release Schedule ](https://www.python.org/dev/peps/pep-0569/)

Adding Python 3.8 to CI

---

stix2matcher/matcher.py
stix2matcher/test/test_complex.py

Sets of bindings were represented as lists. As a consequence a `[...] REPEATS k` would generate all n choose k combinations before returning any binding (where n is the number of matches for [...]).
They are now represented as generators. It is now much faster to get a match.
We still have to try all n choose k combinations when there are no matches (or when one needs all matches), but in any case it consumes much less memory.
Generators can be seen as an implicit form of backtracking in this case.
I added some test cases to demonstrate the speed up.
As mentioned before the no match situation is still slow, that's why `test_combinatorial_explosion_nomatch` is marked `skip`.
The whole test suite (with added tests) takes less than 6s and uses less than 32MB after the patch.
Before the patch …

Use generators instead of lists to limit memory usage and speed up `match`

---

.travis.yml
setup.py
tox.ini

Python 3.9 has been released in October 2020 and it is expected that security updates will be released until approximately October 2025.
[See PEP 596 -- Python 3.9 Release Schedule](https://www.python.org/dev/peps/pep-0596/#id7)

Adding Python 3.9 to CI

---

stix2matcher/matcher.py
stix2matcher/test/test_timestamps.py

strptime raises ValueError in case of nanoseconds precising (i.e. "2021-03-04T12:00:25.639380322Z"),
Maximum supported precision by Datetime is microsecond. 
The proposed change doesn't preserve the nanoseconds it just chops off after 6 decimal places, but it at least won't break parsing in case of more than 6 decimal places.

don't break on precision grater than microsecond

---

stix2matcher/matcher.py
stix2matcher/test/test_complex.py

Addresses issue #67 .
The main idea in this change is to push the "unpacking" of instances to a later stage. It will happen after the initial filtering of the observables, but before the high level operators, like `REPEATS` or `FOLLOWEDBY`.
Based on experiments on real data, created by `stix-shifter` of low level monitoring events, such as EDRs or Sysmon, the boost in performance can be enormous. As an example, there are 15,754 observables generated out of 100 original observables. In another example, there are 189,023 instances generated out of 300 original observables.
When comparing the two above example with a version without instances duplication, the timing is as follows:
Improvement | Time measured for 100 observed_data | % of improvement | Time measured for 300 observed_data | % …

Performance boost

---

stix2matcher/matcher.py
stix2matcher/test/test_binary.py

Return base64 decoded value as string instead of bytes. Is used to search _bin property values with human readable queries.

Stringify base64 decoded bytes for LIKE operator
